{% set version = "0.0.0" %}
{% set name = "BiG-MAP" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: python
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python >=3.6
    - pandas =0.22.0
    - biopython
    - parallel-fastq-dumb
    - mash
    - hmmer
    - samtools
    - bowtie2 
    - bedtools
    - biom-format

test:
  commands:
    - python --version

about:
  home: https://github.com/medema-group/BiG-MAP
  lincense: MIT
  lincense_file: LINCENSE
  summary: "A tool for profiling abundance and expression levels of gen vluster across metagenomic and metatranscriptomic data"